package com.cross.cross_sell.modal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;



@Getter
@Setter
@DynamoDBTable(tableName = "Book")
@Data
public class CrossSell {
@DynamoDBHashKey
@DynamoDBAutoGeneratedKey
private String id;
	@DynamoDBAttribute
	private String crsellValue;
	@DynamoDBAttribute
	private String isAactive;
	@DynamoDBAttribute
	private String productCode;

}
